#!/bin/bash

cd modules

printf "Select a module to copy:\n"
select d in */; do test -n "$d" && break; echo ">>> Invalid Selection"; done


cp -r "$d" /etc/puppet/modules/

echo module copied to /etc/puppet/modules/

