#!/bin/bash

# A script to remove Puppet certificates. Must be run with sudo (and care)

service puppet stop
service puppetmaster stop

rm -rf /var/lib/puppet/ssl/

service puppetmaster start
service puppet start

echo done
