#!/bin/bash

select opt in "${options[@]}" "Stop the script"; do
  case $opt in
    /etc/puppet/modules/*)
      echo "folder $opt selected"
      # processing
      ;;
    "Stop the script")
      echo "You chose to stop"
      break
      ;;
    *)
      echo "This is not a number"
      ;;
  esac
done
